name: raigon_art
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  google_fonts: ^9.0.0
  flutter_launcher_icons: ^0.14.4
  font_awesome_flutter: ^11.0.0
  web: ^1.1.1
  file_picker: ^13.1.0
  desktop_drop: ^0.8.0
  file_saver: ^0.7.0
  http: ^1.6.0
  dir_picker: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
